version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - errcheck
    - errorlint
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
  settings:
    errcheck:
      check-type-assertions: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - std-error-handling
    paths:
      - vendor
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - vendor
