version: "2"
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    errcheck:
      check-type-assertions: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - vendor
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - vendor
